### ISSUE TITLE
NetworkWatcher: Module not found: Error: Can't resolve '_http_agent'

### ISSUE THREAD

**Issue by PacoRivera13** [TrackJs/TrackJS-Node#15]
Versions:
```
"trackjs-node": "1.0.1",
"@angular/core": "^14.0.0",
```

I can't serve my app because of this:
`./node_modules/trackjs-node/dist/watchers/NetworkWatcher.js:13:16-38 - Error: Module not found: Error: Can't resolve '_http_agent' in '{userlocation}\node_modules\trackjs-node\dist\watchers'`

**Comment by toddhgardner** [comment]
Thanks for the report, I'll look into it shortly. What version of node are you using?

**Comment by PacoRivera13** [comment]
> 

**v16.13.2**

**Comment by toddhgardner** [comment]
@PacoRivera13 I think these errors are because you are compiling the NodeJS agent into a browser application. If you are trying to add TrackJS to your client-side angular app, you should use `npm i trackjs` to install the [browser agent](https://www.npmjs.com/package/trackjs) instead.

If I am misunderstanding, can you please elaborate on what server-side things you are doing that you need the `trackjs-node` agent for?

**Comment by PacoRivera13** [comment]
> @PacoRivera13 I think these errors are because you are compiling the NodeJS agent into a browser application. If you are trying to add TrackJS to your client-side angular app, you should use `npm i trackjs` to install the [browser agent](https://www.npmjs.com/package/trackjs) instead.
> 
> If I am misunderstanding, can you please elaborate on what server-side things you are doing that you need the `trackjs-node` agent for?

I'm developing an application using **_ionic framework_**, currently, we have the website allocated and **_trackJS_** agent is logging errors as expected but the apps (iOS/Android) don't log any error on the app.
I enter a ticket with **_trackJS_** Team and they do the suggestion of using **_trackjs-node._**

**Comment by toddhgardner** [comment]
@PacoRivera13 Gotcha, I remember seeing this. You're looking for a solution to support Capacitor. Let me have a look at that, but that's not exactly a bug in this agent.

**Comment by toddhgardner** [comment]
I think we misunderstood and steered you down a bad path. I've been exploring the Capacitor project and I don't think it runs on node, only a wrapper around a web browser.

I don't think you need the TrackJS-Node package at all. Just the [regular browser package](https://www.npmjs.com/package/trackjs). You should be able to add it via npm and do something like this in the "main" starting point of your application:

import { TrackJS } from 'trackjs';
TrackJS.install({token:'YOURTOKEN'});

I have this working in one of the sample applications. 
If that doesn't work for you, can you show me what you are doing or some sample code?
